In [4]:
import numpy as np
import pandas as pd


In [6]:
from google.colab import files
u= files.upload()

Saving homeprices.csv to homeprices.csv


In [7]:
df = pd.read_csv("homeprices.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4      west windsor  4000  725000
5      west windsor  2600  585000
6      west windsor  3800  615000
7      west windsor  3300  650000
8       robinsville  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [8]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 0            0             1
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            1             0
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [9]:
merged = pd.concat([df,dummies], axis='columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4      west windsor  4000  725000                0            0             1
5      west windsor  2600  585000                0            0             1
6      west windsor  3800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8       robinsville  3600  710000                0            1             0
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [10]:
final_data = merged.drop(['town','robinsville'], axis='columns')
final_data

area   price  monroe township  west windsor
0   2600  550000                1             0
1   3000  565000                1             0
2   3200  610000                1             0
3   3600  680000                1             0
4   4000  725000                0             1
5   2600  585000                0             1
6   3800  615000                0             1
7   3300  650000                0             1
8   3600  710000                0             0
9   2600  575000                0             0
10  2900  600000                0             0
11  3100  620000                0             0
12  3600  695000                0             0

In [11]:
from sklearn import linear_model 
r = linear_model.LinearRegression()



In [12]:
final = final_data.drop(['price'], axis='columns')
final

area  monroe township  west windsor
0   2600                1             0
1   3000                1             0
2   3200                1             0
3   3600                1             0
4   4000                0             1
5   2600                0             1
6   3800                0             1
7   3300                0             1
8   3600                0             0
9   2600                0             0
10  2900                0             0
11  3100                0             0
12  3600                0             0

In [13]:
Y = final_data.price
Y


0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [14]:
r.fit(final,Y)

LinearRegression()

In [37]:
r.predict([[3333,0,0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([658015.70441147])

In [32]:
r.score(final,Y)*100

78.37623791551133

In [17]:
import pickle
with open('dummy_pickle','wb') as d:
 pickle.dump(r,d)

In [18]:
with open('dummy_pickle','rb') as d:
  execute = pickle.load(d)

In [19]:
execute.predict([[3333,0,1]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([634169.39418581])

In [23]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()

In [26]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle.town

0     0
1     0
2     0
3     0
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
12    1
Name: town, dtype: int64

In [28]:
X = df[['town','area']] .values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   2, 4000],
       [   2, 2600],
       [   2, 3800],
       [   2, 3300],
       [   1, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [39]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [42]:
r.fit(X,y)

LinearRegression()

In [44]:
r.predict([[2,3323]])

array([644187.33937874])

In [45]:
r.score(X,y)

0.7232562318943262

In [31]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()