In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris



In [2]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
iris.target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, test_size= 0.2)

In [5]:
Lr = LogisticRegression()
Lr.fit(X_train, Y_train)
Lr.score(X_test, Y_test)


0.9666666666666667

In [6]:
support = SVC()
support.fit(X_train, Y_train)
support.score(X_test, Y_test)

0.9

In [7]:
ran = RandomForestClassifier(n_estimators=5)
ran.fit(X_train, Y_train)
ran.score(X_test, Y_test)


0.9666666666666667

In [ ]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=5)
for train_index, test_index in kf.split(iris.data, iris.target):
   print(train_index, test_index)
 


In [9]:
def get_score(model,X_train, X_test, Y_train, Y_test):
  model.fit(X_train, Y_train)
  return model.score(X_test, Y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
sk = StratifiedKFold(n_splits= 3)
L_score= []
SVC_score= []
RF_score= []
for train_index, test_index in sk.split(iris.data, iris.target):
  X_train, X_test, Y_train, Y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]
  L_score.append(get_score(LogisticRegression(max_iter=500, solver='liblinear' ), X_train, X_test, Y_train, Y_test))
  SVC_score.append(get_score(SVC(gamma='auto'), X_train, X_test, Y_train, Y_test))
  RF_score.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, Y_train, Y_test))
                                                                                      



In [13]:
print(list(L_score))
def aver(s):
  return sum(s)/ len(s)
aver(L_score)



[0.96, 0.96, 0.94]


0.9533333333333333

In [ ]:
print(list(SVC_score))
aver(SVC_score)

[0.98, 0.98, 0.96]


0.9733333333333333

In [ ]:
print(list(RF_score))
aver(RF_score)

[0.98, 0.94, 0.98]


0.9666666666666667

In [ ]:
# Using cross_value_score
from sklearn.model_selection import cross_val_score
score_1 = cross_val_score(LogisticRegression(max_iter=500), iris.data, iris.target, cv=4)
score_2 = cross_val_score(SVC(), iris.data, iris.target, cv=4)
score_3 = cross_val_score(RandomForestClassifier(n_estimators=50), iris.data, iris.target, cv=4)




In [ ]:
average(score_2)


0.9731507823613088

In [ ]:
score_1


array([0.97368421, 0.94736842, 0.94594595, 0.97297297])

In [ ]:
score_2

array([0.97368421, 1.        , 0.94594595, 0.97297297])

In [ ]:
score_3

array([0.97368421, 0.94736842, 0.94594595, 0.97297297])

In [ ]:
average(score_1)

0.9733285917496444

In [ ]:

average(score_3)


0.9599928876244666