In [12]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [11]:
from google.colab import files
u= files.upload()

Saving rates.csv to rates.csv


In [13]:
df = pd.read_csv("rates.csv")
df

area  bedroom  age   price
0  2300      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   17  610000
3  3700      3.0   31  680000
4  4000      4.0    8  725000

In [14]:
median_bedroom = int(df.bedroom.median())

In [15]:
df.bedroom = df.bedroom.fillna(median_bedroom)
df

area  bedroom  age   price
0  2300      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   17  610000
3  3700      3.0   31  680000
4  4000      4.0    8  725000

In [16]:
regr = linear_model.LinearRegression()
regr.fit(df[['area', 'bedroom', 'age']], df.price)

LinearRegression()

In [18]:
regr.intercept_

386269.21736099414

In [19]:
regr.coef_

array([   115.67282552, -32830.66062402,  -1287.08384173])

In [21]:
regr.predict([[3333,3,17]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([651434.33763291])

In [20]:
115.67*3333 + (-32830.66*3) + (-1287.083*17) + 386269.217

651424.936

In [22]:
import pickle 


In [23]:
with open("model_pickle", "wb") as f:
 pickle.dump(regr,f)

In [26]:
with open("model_pickle","rb") as f:
  mp = pickle.load(f)

In [27]:
mp.predict([[5000,4,16]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([812717.36099006])